steps:
  - name: 'docker:latest'
    env:
      - 'GROUP=gcr.io/sock-shop-releases'
      - 'COMMIT=$SHORT_SHA'
    args: ['./scripts/build.sh']

  - name: 'gcr.io/sock-shop-releases/catalogue-dev'
    entrypoint: "gvt"
    args: ["restore"]   

  - name: 'gcr.io/cloud-builders/go'
    env: ["PROJECT_ROOT=github.com/microservices-demo/catalogue"]
    args: ["test", "-v", "-covermode=count", "-coverprofile=coverage.out"]

  - name: 'docker:latest'
    args: ['./test/test.sh', 'container.py', '--tag', '$SHORT_SHA' ]

  - name: 'gcr.io/sock-shop-releases/catalogue-dev'
    entrypoint: "sh"
    args: ["-c", "goveralls -coverprofile=coverage.out -repotoken=$$COVERALLS_TOKEN"]
    secretEnv: ['COVERALLS_TOKEN']
    
images:
- 'gcr.io/sock-shop-releases/catalogue'

secrets:
- kmsKeyName: projects/sock-shop-releases/locations/global/keyRings/sock-shop/cryptoKeys/secrets
  secretEnv:
    COVERALLS_TOKEN: "CiQAkTDQ4r3fSZniqJmuYCVLN0zpwzG1KFDYNlUAnSnA1Qkvz3YSSgCGYwtp7Nnys5uzrHJZQxW/kiSQXuOy66phkiABGNfELKxbE70XwDqwLDCxaEfQ1CVbxCV6MyUPQ9itSq722FvBFvXhbIqqrafh"

