steps:
  - name: 'docker:latest'
    env:
      - 'GROUP=gcr.io/sock-shop-releases'
      - 'COMMIT=latest'
    args: ['./scripts/build.sh']
  - name: 'docker:latest'
    args: ['./test/test.sh', 'unit.py' ]
  - name: 'docker:latest'
    args: ['./test/test.sh', 'container.py', '--tag', 'latest' ]
images:
- 'gcr.io/sock-shop-releases/catalogue'
